name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      HANGAR_TOKEN: ${{ secrets.HANGAR_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish to Modrinth
        run: |
          chmod +x ./gradlew \
          ./gradlew modrinth
      - name: Publish to Hangar
        run: ./gradlew publishAllPublicationsToHangar
      - name: Build for GitHub
        run: ./gradlew build
      - name: Publish to GitHub
        uses: xresloader/upload-to-github-release@v1
        with:
          file: "*!(dev).jar"
          update_latest_release: true